// Components
import Navbar from "./components/navbar";
import Footer from "./components/footer";

// Providers
import { Providers } from "./providers";

// APP CSS
import "./styles/App.css";

// Next metadata
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="flex flex-col min-h-svh">
        <main className="flex flex-col flex-grow">
          <Providers>
            <Navbar />
            {children}
          </Providers>
          <Footer />
        </main>
      </body>
    </html>
  );
}
