// React
import { useState, useEffect } from "react";
// import { Routes, Route } from "react-router-dom";

// Components
import Navbar from "./components/navbar";
// import Footer from "./components/footer";

// Pages
// import Home from "./home";
// import Products from "./products/page";
// import About from "./about/page";
// import Product from "./products/[slug]/page";

// Context
import { CartContext } from "./utils/contexts";

// Chakra UI - APP CSS
import { Providers } from "./providers";
import "./styles/App.css";

interface CartItem {
  id: number;
  color?: string;
  size?: string;
  discount: number;
  quantity: number;
}

const [cart, setCart] = useState<CartItem[]>([]);
useEffect(() => {
  console.log("CART CONTEXT");
  console.log(cart);
  console.log("CART LENGTH");
  console.log(cart.length);
}, [cart]);

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <CartContext.Provider value={{ data: cart, update: setCart }}>
      <html lang="en">
        <main className="flex flex-col flex-grow bg-background">
          <Navbar />
          <body>{children}</body>
          {/* <Footer /> */}
        </main>
        </html>
      </CartContext.Provider>
    </Providers>
  );
}
